builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/lolcat.go
checksum:
  name_template: 'checksums.txt'
nfpm:
  vendor: sw0x2A
  homepage: https://github.com/sw0x2A/lolcat
  maintainer: sw0x2A <sw@00101010.org>
  description: Simplified implementation of lolcat in Go.
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
